version: '3.9'

volumes:
  svr_video_data:
    external: false
  svr_postgres_data:
    external: false

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: svr_sm_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  postgres:
    image: postgres:15.2-alpine
    container_name: svr_sm_db
    restart: unless-stopped
    volumes:
      - ./services/postgres/init:/docker-entrypoint-initdb.d
      - svr_postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: svr_sm_api
    restart: unless-stopped
    volumes:
      - svr_video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - 8080:8080

  source_processor:
    build:
      context: .
      dockerfile: ./services/source_processor/Dockerfile
    container_name: svr_sm_source_processor
    restart: unless-stopped
    volumes:
      - svr_video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres


