version: '3.9'

volumes:
  video_data:
    external: false
  postgres_data:
    external: false

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: svr_sm_db
    restart: unless-stopped
    volumes:
      - ./services/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: svr_sm_api
    restart: unless-stopped
    volumes:
      - video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres

  source_processor:
    build:
      context: .
      dockerfile: ./services/source_processor/Dockerfile
    container_name: svr_sm_source_processor
    restart: unless-stopped
    volumes:
      - video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres

  nginx:
    build: ./services/nginx
    container_name: svr_sm_nginx
    restart: unless-stopped
    ports:
      - 8085:8080
    depends_on:
      - api


