version: '3.9'

volumes:
  svr_video_data:
    external: true
  svr_postgres_data:
    external: true

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: svr_sm_db
    restart: unless-stopped
    volumes:
      - ./services/postgres/init:/docker-entrypoint-initdb.d
      - svr_postgres_data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    container_name: svr_sm_api
    restart: unless-stopped
    volumes:
      - svr_video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - 8080:8080

  source_processor:
    build:
      c	ontext: .
      dockerfile: ./services/source_processor/Dockerfile
    container_name: svr_sm_source_processor
    restart: unless-stopped
    volumes:
      - svr_video_data:/home/video_data
      - ./credentials:/home/credentials
    env_file: ./.env
    depends_on:
      - postgres

